use_frameworks!

platform :ios, '9.0'

target 'SwiftUIKitExtensions_Example' do
#  pod 'SwiftUIKitExtensions', :path => '../'
  pod 'SwiftUIKitExtensions'


  target 'SwiftUIKitExtensions_Tests' do
    inherit! :search_paths

    
  end
end
